Dim swApp As Object
Dim longstatus As Long, longwarnings As Long
Sub main()
Dim swApp As Object
Dim Part As Object
Dim boolstatus As Boolean
Set swApp = Application.SldWorks
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
boolstatus = Part.InsertCurveFile("/Users/nathanaeljenkins/Documents/University/ICLR/CODE/MATLAB-SW\examples\sections\section_1.sldcrv")
boolstatus = Part.InsertCurveFile("/Users/nathanaeljenkins/Documents/University/ICLR/CODE/MATLAB-SW\examples\sections\section_2.sldcrv")
boolstatus = Part.InsertCurveFile("/Users/nathanaeljenkins/Documents/University/ICLR/CODE/MATLAB-SW\examples\sections\section_3.sldcrv")
boolstatus = Part.InsertCurveFile("/Users/nathanaeljenkins/Documents/University/ICLR/CODE/MATLAB-SW\examples\sections\section_4.sldcrv")
boolstatus = Part.InsertCurveFile("/Users/nathanaeljenkins/Documents/University/ICLR/CODE/MATLAB-SW\examples\sections\section_5.sldcrv")
boolstatus = Part.InsertCurveFile("/Users/nathanaeljenkins/Documents/University/ICLR/CODE/MATLAB-SW\examples\sections\section_6.sldcrv")
boolstatus = Part.InsertCurveFile("/Users/nathanaeljenkins/Documents/University/ICLR/CODE/MATLAB-SW\examples\sections\section_7.sldcrv")
boolstatus = Part.InsertCurveFile("/Users/nathanaeljenkins/Documents/University/ICLR/CODE/MATLAB-SW\examples\sections\section_8.sldcrv")
boolstatus = Part.InsertCurveFile("/Users/nathanaeljenkins/Documents/University/ICLR/CODE/MATLAB-SW\examples\sections\section_9.sldcrv")
boolstatus = Part.InsertCurveFile("/Users/nathanaeljenkins/Documents/University/ICLR/CODE/MATLAB-SW\examples\sections\section_10.sldcrv")
boolstatus = Part.InsertCurveFile("/Users/nathanaeljenkins/Documents/University/ICLR/CODE/MATLAB-SW\examples\sections\section_11.sldcrv")
boolstatus = Part.InsertCurveFile("/Users/nathanaeljenkins/Documents/University/ICLR/CODE/MATLAB-SW\examples\sections\section_12.sldcrv")
boolstatus = Part.InsertCurveFile("/Users/nathanaeljenkins/Documents/University/ICLR/CODE/MATLAB-SW\examples\sections\section_13.sldcrv")
boolstatus = Part.InsertCurveFile("/Users/nathanaeljenkins/Documents/University/ICLR/CODE/MATLAB-SW\examples\sections\section_14.sldcrv")
boolstatus = Part.InsertCurveFile("/Users/nathanaeljenkins/Documents/University/ICLR/CODE/MATLAB-SW\examples\sections\section_15.sldcrv")
boolstatus = Part.InsertCurveFile("/Users/nathanaeljenkins/Documents/University/ICLR/CODE/MATLAB-SW\examples\sections\section_16.sldcrv")
boolstatus = Part.InsertCurveFile("/Users/nathanaeljenkins/Documents/University/ICLR/CODE/MATLAB-SW\examples\sections\section_17.sldcrv")
boolstatus = Part.InsertCurveFile("/Users/nathanaeljenkins/Documents/University/ICLR/CODE/MATLAB-SW\examples\sections\section_18.sldcrv")
boolstatus = Part.InsertCurveFile("/Users/nathanaeljenkins/Documents/University/ICLR/CODE/MATLAB-SW\examples\sections\section_19.sldcrv")
boolstatus = Part.InsertCurveFile("/Users/nathanaeljenkins/Documents/University/ICLR/CODE/MATLAB-SW\examples\sections\section_20.sldcrv")
boolstatus = Part.InsertCurveFile("/Users/nathanaeljenkins/Documents/University/ICLR/CODE/MATLAB-SW\examples\sections\section_21.sldcrv")
boolstatus = Part.InsertCurveFile("/Users/nathanaeljenkins/Documents/University/ICLR/CODE/MATLAB-SW\examples\sections\section_22.sldcrv")
boolstatus = Part.InsertCurveFile("/Users/nathanaeljenkins/Documents/University/ICLR/CODE/MATLAB-SW\examples\sections\section_23.sldcrv")
boolstatus = Part.InsertCurveFile("/Users/nathanaeljenkins/Documents/University/ICLR/CODE/MATLAB-SW\examples\sections\section_24.sldcrv")
boolstatus = Part.InsertCurveFile("/Users/nathanaeljenkins/Documents/University/ICLR/CODE/MATLAB-SW\examples\sections\section_25.sldcrv")
boolstatus = Part.InsertCurveFile("/Users/nathanaeljenkins/Documents/University/ICLR/CODE/MATLAB-SW\examples\sections\section_26.sldcrv")
boolstatus = Part.Extension.SelectByID2("Curve25", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve26", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
Part.FeatureManager.InsertProtrusionBlend False, True, False, 1, 0, 0, 1, 1, True, True, False, 0, 0, 0, True, True, True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Curve24", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve25", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
Part.FeatureManager.InsertProtrusionBlend False, True, False, 1, 0, 0, 1, 1, True, True, False, 0, 0, 0, True, True, True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Curve23", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve24", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
Part.FeatureManager.InsertProtrusionBlend False, True, False, 1, 0, 0, 1, 1, True, True, False, 0, 0, 0, True, True, True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Curve22", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve23", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
Part.FeatureManager.InsertProtrusionBlend False, True, False, 1, 0, 0, 1, 1, True, True, False, 0, 0, 0, True, True, True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Curve21", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve22", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
Part.FeatureManager.InsertProtrusionBlend False, True, False, 1, 0, 0, 1, 1, True, True, False, 0, 0, 0, True, True, True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Curve20", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve21", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
Part.FeatureManager.InsertProtrusionBlend False, True, False, 1, 0, 0, 1, 1, True, True, False, 0, 0, 0, True, True, True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Curve19", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve20", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
Part.FeatureManager.InsertProtrusionBlend False, True, False, 1, 0, 0, 1, 1, True, True, False, 0, 0, 0, True, True, True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Curve18", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve19", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
Part.FeatureManager.InsertProtrusionBlend False, True, False, 1, 0, 0, 1, 1, True, True, False, 0, 0, 0, True, True, True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Curve17", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve18", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
Part.FeatureManager.InsertProtrusionBlend False, True, False, 1, 0, 0, 1, 1, True, True, False, 0, 0, 0, True, True, True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Curve16", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve17", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
Part.FeatureManager.InsertProtrusionBlend False, True, False, 1, 0, 0, 1, 1, True, True, False, 0, 0, 0, True, True, True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Curve15", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve16", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
Part.FeatureManager.InsertProtrusionBlend False, True, False, 1, 0, 0, 1, 1, True, True, False, 0, 0, 0, True, True, True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Curve14", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve15", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
Part.FeatureManager.InsertProtrusionBlend False, True, False, 1, 0, 0, 1, 1, True, True, False, 0, 0, 0, True, True, True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Curve13", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve14", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
Part.FeatureManager.InsertProtrusionBlend False, True, False, 1, 0, 0, 1, 1, True, True, False, 0, 0, 0, True, True, True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Curve12", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve13", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
Part.FeatureManager.InsertProtrusionBlend False, True, False, 1, 0, 0, 1, 1, True, True, False, 0, 0, 0, True, True, True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Curve11", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve12", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
Part.FeatureManager.InsertProtrusionBlend False, True, False, 1, 0, 0, 1, 1, True, True, False, 0, 0, 0, True, True, True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Curve10", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve11", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
Part.FeatureManager.InsertProtrusionBlend False, True, False, 1, 0, 0, 1, 1, True, True, False, 0, 0, 0, True, True, True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Curve9", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve10", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
Part.FeatureManager.InsertProtrusionBlend False, True, False, 1, 0, 0, 1, 1, True, True, False, 0, 0, 0, True, True, True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Curve8", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve9", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
Part.FeatureManager.InsertProtrusionBlend False, True, False, 1, 0, 0, 1, 1, True, True, False, 0, 0, 0, True, True, True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Curve7", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve8", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
Part.FeatureManager.InsertProtrusionBlend False, True, False, 1, 0, 0, 1, 1, True, True, False, 0, 0, 0, True, True, True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Curve6", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve7", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
Part.FeatureManager.InsertProtrusionBlend False, True, False, 1, 0, 0, 1, 1, True, True, False, 0, 0, 0, True, True, True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Curve5", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve6", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
Part.FeatureManager.InsertProtrusionBlend False, True, False, 1, 0, 0, 1, 1, True, True, False, 0, 0, 0, True, True, True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Curve4", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve5", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
Part.FeatureManager.InsertProtrusionBlend False, True, False, 1, 0, 0, 1, 1, True, True, False, 0, 0, 0, True, True, True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Curve3", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve4", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
Part.FeatureManager.InsertProtrusionBlend False, True, False, 1, 0, 0, 1, 1, True, True, False, 0, 0, 0, True, True, True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Curve2", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve3", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
Part.FeatureManager.InsertProtrusionBlend False, True, False, 1, 0, 0, 1, 1, True, True, False, 0, 0, 0, True, True, True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Curve1", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve2", "REFERENCECURVES", 0, 0, 0, True, 1, Nothing, 0)
Part.FeatureManager.InsertProtrusionBlend False, True, False, 1, 0, 0, 1, 1, True, True, False, 0, 0, 0, True, True, True
Part.ClearSelection2 True
Set swApp = Application.SldWorks
End Sub